feat: consider feedback of the first prototype round
alyf-de/arbeitszeiterfassung_s4a pull request #2
Opened 2023-08-03 14:47 UTC by PatrickDEissler

2023-08-03 15:18 UTC, barredterra requested changes

2023-08-03 15:18 UTC, barredterra commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/doctype/working_time/working_time.js
>  		}
```suggestion
		if (frm.doc.time_logs.length > 1) {
			prev_row = frm.doc.time_logs.at(-2);
			if (!prev_row.to_time || prev_row.to_time.trim() === "") {
				frappe.model.set_value(cdt, prev_row.name, "to_time", frappe.datetime.now_time(false));
			}
		}
```

So können wir uns eine Variable sparen und es ist klarer, wo die Daten herkommen

2023-08-03 15:18 UTC, barredterra commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/doctype/working_time/working_time.py
> +default_activity = frappe.db.get_single_value('Working Time Settings', 'default_activity')
Das sollte keine globale Variable sein. Besser in eine Funktion `get_default_activity` verpacken:

```py
def get_default_activity():
	return frappe.db.get_single_value("Working Time Settings", "default_activity")
```

Und bitte auf eine einheitliche Formatierung achten (doppelte Anführungszeichen)

2023-08-03 15:27 UTC, barredterra commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/employee_checkin/employee_checkin.py
> +
```suggestion
		if len(working_time.time_logs) > 1 and not working_time.time_logs[-2].to_time:
			working_time.time_logs[-2].to_time = str(checkin_time)
```

2023-08-03 15:30 UTC, barredterra commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/employee_checkin/employee_checkin.py
Wir konvertieren die `checkin_time` an vier Stellen in einen String. Es wäre sinnvoller, wenn wir das nur einmal, direkt bei der definition machen:

```py
checkin_time = str(datetime.time())
```

2023-08-08 13:30 UTC, PatrickDEissler reviewed
This commit is unnecassary. I have not seen my previous commit (5e69a9a8e931167a45c9887e9677745d58139437) in the branch, but now I see that it was already there

2023-08-08 13:31 UTC, PatrickDEissler commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/doctype/working_time/working_time.js
>  		}
@barredterra 
Danke.
Habe ich so berücksichtigt mit kleinen Änderungen (Variable oberhalb des If-Statements und prev_to_time an anderen Stellen ersetzt).

2023-08-08 14:21 UTC, PatrickDEissler commented
@barredterra 
Danke für die Tipps und Hinweise. Ich habe sie aufgenommen und paar weitere Commits gepusht.

2023-08-08 14:37 UTC, barredterra commented on arbeitszeiterfassung_s4a/arbeitszeiterfassung_s4a/doctype/working_time/working_time.py
> +	return frappe.db.get_single_value("Working Time Settings", "default_activity")
```suggestion
    return frappe.db.get_single_value("Working Time Settings", "default_activity")
```

Der Rest der Datei nutzt vier Leerzeichen für die Einrückung

2023-08-08 15:11 UTC, PatrickDEissler commented
@barredterra Danke. Ich werde in Zukunft mehr auf solche Themen wie Indentation und "Style" achten.

2023-08-08 18:15 UTC, barredterra approved these changes

2023-08-08 18:15 UTC, merged